//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleCustomer.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerDbHistory
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public SimpleCustomer.Core.Gender Gender { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public SimpleCustomer.Core.Category Category { get; set; }
        public string HouseNumber { get; set; }
        public string AddressLineOne { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public ModificationType ModificationType { get; set; }
        public string ChangedOn { get; set; }
    }
}
