//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleCustomer.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CustomersContext : DbContext
    {
        public CustomersContext()
            : base("name=CustomersContext")
        {
            CustomerDbs = Set<CustomerDb>();
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        internal virtual DbSet<CustomerDb> CustomerDbs { get; set; }
        public virtual DbSet<CustomerDbHistory> CustomerDbHistories { get; set; }
    }
}
