//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleCustomer.Data
{
    using System;
    
    public enum ModificationType : byte
    {
        Add = 0,
        Remove = 1,
        Update = 2,
        Other = 3
    }
}
